#Task Description  
Accept input as a local file and return a numpy array containing a 5 x [No. of frames] matrix. The matrix should contain a row for each frame of the video. The columns are as follows:  
[player fallen in frame or not, x coordinate, y coordinate, width of player, height of player]  

Note that x,y,w,h must be integral values  

Do not rescale the video. Outputs will be checked using RMSE, assuming a resolution of [Resolution]  







In [8]:
from ultralytics import YOLO

model = YOLO("yolov8m.pt")
result = model.predict("manc.mp4", save = True)



WARNING  inference results will accumulate in RAM unless `stream=True` is passed, causing potential out-of-memory
errors for large sources or long-running streams and videos. See https://docs.ultralytics.com/modes/predict/ for help.

Example:
    results = model(source=..., stream=True)  # generator of Results objects
    for r in results:
        boxes = r.boxes  # Boxes object for bbox outputs
        masks = r.masks  # Masks object for segment masks outputs
        probs = r.probs  # Class probabilities for classification outputs

video 1/1 (frame 1/192) c:\Users\shiva\OneDrive\Desktop\BOSM project\fallen players\manc.mp4: 352x640 16 persons, 445.2ms
video 1/1 (frame 2/192) c:\Users\shiva\OneDrive\Desktop\BOSM project\fallen players\manc.mp4: 352x640 15 persons, 352.2ms
video 1/1 (frame 3/192) c:\Users\shiva\OneDrive\Desktop\BOSM project\fallen players\manc.mp4: 352x640 15 persons, 365.4ms
video 1/1 (frame 4/192) c:\Users\shiva\OneDrive\Desktop\BOSM project\fallen players\manc.mp4

In [16]:
print(result[0:192])

[ultralytics.engine.results.Results object with attributes:

boxes: ultralytics.engine.results.Boxes object
keypoints: None
masks: None
names: {0: 'person', 1: 'bicycle', 2: 'car', 3: 'motorcycle', 4: 'airplane', 5: 'bus', 6: 'train', 7: 'truck', 8: 'boat', 9: 'traffic light', 10: 'fire hydrant', 11: 'stop sign', 12: 'parking meter', 13: 'bench', 14: 'bird', 15: 'cat', 16: 'dog', 17: 'horse', 18: 'sheep', 19: 'cow', 20: 'elephant', 21: 'bear', 22: 'zebra', 23: 'giraffe', 24: 'backpack', 25: 'umbrella', 26: 'handbag', 27: 'tie', 28: 'suitcase', 29: 'frisbee', 30: 'skis', 31: 'snowboard', 32: 'sports ball', 33: 'kite', 34: 'baseball bat', 35: 'baseball glove', 36: 'skateboard', 37: 'surfboard', 38: 'tennis racket', 39: 'bottle', 40: 'wine glass', 41: 'cup', 42: 'fork', 43: 'knife', 44: 'spoon', 45: 'bowl', 46: 'banana', 47: 'apple', 48: 'sandwich', 49: 'orange', 50: 'broccoli', 51: 'carrot', 52: 'hot dog', 53: 'pizza', 54: 'donut', 55: 'cake', 56: 'chair', 57: 'couch', 58: 'potted plant'

In [18]:
frames = []

In [23]:
for  j in range(192):
    frames.append([0,0,0,0,0])
    for i in result[j].boxes:
        if list(i.cls) == [0.]:
            x,y,w,h = list(i.xywh)[0]
            if w>1.5*h:
                frames[-1][0] = 1
                x = int(x)
                y = int(y)
                w = int(w)
                h = int(h)
                frames[-1][1:] = [x,y,w,h]
                print(frames[-1])


[1, 798, 378, 63, 37]
[1, 798, 378, 63, 37]
[1, 845, 392, 78, 41]
[1, 845, 392, 79, 41]
[1, 843, 391, 72, 45]
[1, 842, 392, 73, 45]
[1, 840, 390, 71, 47]
[1, 742, 120, 50, 30]
[1, 738, 123, 47, 30]
[1, 149, 55, 294, 110]
[1, 294, 52, 177, 103]
[1, 149, 55, 295, 110]
[1, 294, 52, 177, 103]
[1, 216, 74, 429, 144]
[1, 216, 74, 428, 144]
[1, 131, 80, 240, 158]
[1, 258, 108, 355, 213]
[1, 378, 112, 542, 221]
[1, 378, 112, 541, 221]
[1, 380, 112, 541, 222]
[1, 379, 112, 540, 222]
[1, 379, 112, 540, 222]
[1, 379, 112, 540, 222]
[1, 379, 112, 541, 222]
[1, 378, 112, 541, 222]
[1, 378, 112, 540, 222]
[1, 379, 112, 540, 222]
[1, 379, 112, 540, 222]
[1, 379, 112, 541, 222]
[1, 378, 112, 541, 222]
[1, 378, 112, 541, 222]
[1, 378, 112, 541, 222]
[1, 378, 112, 541, 222]
[1, 378, 112, 541, 222]
[1, 378, 112, 541, 222]
[1, 378, 112, 541, 222]
[1, 378, 112, 541, 222]
[1, 378, 112, 540, 222]
[1, 378, 112, 540, 221]
[1, 378, 112, 540, 222]
[1, 378, 112, 540, 222]
[1, 378, 112, 540, 222]
[1, 378, 112, 540

In [24]:
import numpy as np

In [25]:
fin = np.matrix(frames)

In [26]:
print(fin)

[[          0           0           0           0           0]
 [          0           0           0           0           0]
 [          0           0           0           0           0]
 ...
 [          1         378         112         540         222]
 [          1         378         112         540         222]
 [          1         378         112         540         222]]
